# Generated by Django 5.1.7 on 2025-04-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmember',
            name='date_joined',
        ),
    ]
